In [1]:
import numpy as np
from torch.utils.data import Dataset, DataLoader

class RandomDataset(Dataset):
    def __getitem__(self, index):
        return np.random.randint(0, 1000, 3)

    def __len__(self):
        return 16
    
dataset = RandomDataset()
dataloader = DataLoader(dataset, batch_size=2, num_workers=4)
for batch in dataloader:
    print(batch)

tensor([[583, 140, 570],
        [271,  13, 703]])
tensor([[591, 507, 123],
        [785,  89, 347]])
tensor([[789, 738,  61],
        [930, 312, 449]])
tensor([[384, 813, 552],
        [464, 592, 927]])
tensor([[968,  64, 776],
        [830, 596, 623]])
tensor([[694, 108, 986],
        [955, 652, 539]])
tensor([[164,  65, 927],
        [310,  23, 558]])
tensor([[499,  32, 417],
        [921, 293, 215]])
